#NAME: Forrest Burton, Conner Yang
#EMAIL: burton.forrest10@gmail.com, conneryang@g.ucla.edu
#ID: 005324612, 905417287

default:
	gcc -Wall -Wextra -g -o lab3a lab3a.c 

dist: default
	tar -czvf lab3a-905417287.tar.gz lab3a.c README Makefile ext2_fs.h

clean:
	rm -f lab3a *tar.gz
